[tasks.wasm_build]
script = [
    "cargo build --release --target wasm32-unknown-unknown "
]

[tasks.assemble_web_files]
dependencies = ["wasm_build"]
script = [
    "wasm-bindgen target/wasm32-unknown-unknown/release/bevy_rltk.wasm --out-dir wasm --no-modules --no-typescript "
]

[tasks.web_build]
dependencies = ["assemble_web_files"]

[tasks.host]
script = [
    "basic-http-server"
]